export const TOP_LEVEL_GROUPS = Object.freeze([
  "中餐",
  "西餐",
  "日料",
  "韩餐",
  "东南亚",
  "快餐小吃",
  "轻食甜品",
]);

export const CHINESE_CUISINES = Object.freeze([
  "川湘菜",
  "粤菜",
  "江浙菜",
  "北方菜",
  "西北菜",
  "云贵菜",
  "广西风味",
  "火锅烧烤",
  "面食",
]);

const mealTags = Object.freeze(["午餐", "晚餐"]);
const normalSpend = Object.freeze(["正常吃"]);

function createFood(id, name, group, cuisine, overrides = {}) {
  return Object.freeze({
    id,
    name,
    group,
    cuisine,
    ...overrides,
    meals: Object.freeze([...(overrides.meals ?? mealTags)]),
    flavors: Object.freeze([...(overrides.flavors ?? ["来点硬菜"])]),
    spends: Object.freeze([...(overrides.spends ?? normalSpend)]),
    visual: overrides.visual ?? "dish",
  });
}

export const FOODS = Object.freeze([
  createFood("mapo-tofu", "麻婆豆腐", "中餐", "川湘菜", { flavors: ["想吃辣", "来点硬菜"] }),
  createFood("kung-pao-chicken", "宫保鸡丁", "中餐", "川湘菜", { flavors: ["想吃辣", "来点硬菜"] }),
  createFood("twice-cooked-pork", "回锅肉", "中餐", "川湘菜", { flavors: ["想吃辣", "来点硬菜"] }),
  createFood("white-cut-chicken", "白切鸡", "中餐", "粤菜", { flavors: ["清淡点"] }),
  createFood("cantonese-roast-goose", "烧鹅", "中餐", "粤菜", { flavors: ["来点硬菜"], spends: ["正常吃", "犒劳自己"] }),
  createFood("claypot-rice", "煲仔饭", "中餐", "粤菜", { flavors: ["来点硬菜"], visual: "rice" }),
  createFood("dongpo-pork", "东坡肉", "中餐", "江浙菜", { flavors: ["来点硬菜"], spends: ["正常吃", "犒劳自己"] }),
  createFood("west-lake-fish", "西湖醋鱼", "中餐", "江浙菜", { flavors: ["清淡点"] }),
  createFood("longjing-shrimp", "龙井虾仁", "中餐", "江浙菜", { flavors: ["清淡点"], spends: ["正常吃", "犒劳自己"] }),
  createFood("beijing-roast-duck", "北京烤鸭", "中餐", "北方菜", { flavors: ["来点硬菜"], spends: ["正常吃", "犒劳自己"] }),
  createFood("pork-stew-noodles", "猪肉炖粉条", "中餐", "北方菜", { flavors: ["来点硬菜"], visual: "noodles" }),
  createFood("di-san-xian", "地三鲜", "中餐", "北方菜", { flavors: ["清淡点"] }),
  createFood("lamb-skewers", "羊肉串", "中餐", "西北菜", { meals: ["午餐", "晚餐", "夜宵"], flavors: ["想吃辣", "来点硬菜"], visual: "skewers" }),
  createFood("saozi-noodles", "臊子面", "中餐", "西北菜", { flavors: ["想吃辣"], visual: "noodles" }),
  createFood("roujiamo", "肉夹馍", "中餐", "西北菜", { meals: ["早餐", "午餐", "晚餐"], flavors: ["来点硬菜"], spends: ["简单吃"], visual: "sandwich" }),
  createFood("crossing-bridge-noodles", "过桥米线", "中餐", "云贵菜", { flavors: ["清淡点"], visual: "noodles" }),
  createFood("steam-pot-chicken", "汽锅鸡", "中餐", "云贵菜", { flavors: ["清淡点", "来点硬菜"] }),
  createFood("guizhou-sour-soup-fish", "酸汤鱼", "中餐", "云贵菜", { flavors: ["想吃辣", "来点硬菜"] }),
  createFood("luosifen", "螺蛳粉", "中餐", "广西风味", { meals: ["午餐", "晚餐", "夜宵"], flavors: ["想吃辣", "来点硬菜"], spends: ["简单吃", "正常吃"], visual: "noodles" }),
  createFood("guangxi-lemon-duck", "柠檬鸭", "中餐", "广西风味", { flavors: ["想吃辣", "来点硬菜"] }),
  createFood("guangxi-stuffed-snails", "酿田螺", "中餐", "广西风味", { meals: ["晚餐", "夜宵"], flavors: ["想吃辣"], visual: "snails" }),
  createFood("spicy-hotpot", "麻辣火锅", "中餐", "火锅烧烤", { flavors: ["想吃辣", "来点硬菜"], spends: ["正常吃", "犒劳自己"], visual: "hotpot" }),
  createFood("tomato-hotpot", "番茄火锅", "中餐", "火锅烧烤", { flavors: ["清淡点", "来点硬菜"], spends: ["正常吃", "犒劳自己"], visual: "hotpot" }),
  createFood("grilled-fish", "烤鱼", "中餐", "火锅烧烤", { flavors: ["想吃辣", "来点硬菜"], visual: "fish" }),
  createFood("beef-noodles", "兰州牛肉面", "中餐", "面食", { meals: ["早餐", "午餐", "晚餐"], flavors: ["清淡点", "来点硬菜"], spends: ["简单吃"], visual: "noodles" }),
  createFood("zhajiang-noodles", "炸酱面", "中餐", "面食", { flavors: ["来点硬菜"], spends: ["简单吃"], visual: "noodles" }),
  createFood("xiaolongbao", "小笼包", "中餐", "面食", { meals: ["早餐", "午餐"], flavors: ["清淡点"], spends: ["简单吃"], visual: "dumplings" }),

  createFood("margherita-pizza", "玛格丽特披萨", "西餐", "意式", { flavors: ["清淡点"], visual: "pizza" }),
  createFood("spaghetti-bolognese", "肉酱意面", "西餐", "意式", { flavors: ["来点硬菜"], visual: "pasta" }),
  createFood("mushroom-risotto", "蘑菇烩饭", "西餐", "意式", { flavors: ["清淡点"], visual: "rice" }),
  createFood("new-york-burger", "纽约牛肉汉堡", "西餐", "美式", { flavors: ["来点硬菜"], visual: "burger" }),
  createFood("buffalo-wings", "水牛城辣鸡翅", "西餐", "美式", { meals: ["午餐", "晚餐", "夜宵"], flavors: ["想吃辣", "来点硬菜"], visual: "wings" }),
  createFood("caesar-salad", "凯撒沙拉", "西餐", "美式", { flavors: ["清淡点"], spends: ["简单吃"], visual: "salad" }),
  createFood("steak-frites", "牛排薯条", "西餐", "法式", { flavors: ["来点硬菜"], spends: ["犒劳自己"], visual: "steak" }),
  createFood("onion-soup", "法式洋葱汤", "西餐", "法式", { flavors: ["清淡点"], visual: "soup" }),
  createFood("croque-monsieur", "法式火腿芝士三明治", "西餐", "法式", { flavors: ["来点硬菜"], visual: "sandwich" }),
  createFood("fish-and-chips", "炸鱼薯条", "西餐", "英式", { flavors: ["来点硬菜"], visual: "fish" }),
  createFood("shepherds-pie", "牧羊人派", "西餐", "英式", { flavors: ["来点硬菜"], visual: "pie" }),

  createFood("salmon-sashimi", "三文鱼刺身", "日料", "刺身寿司", { flavors: ["清淡点"], spends: ["正常吃", "犒劳自己"], visual: "sashimi" }),
  createFood("tuna-sushi", "金枪鱼寿司", "日料", "刺身寿司", { flavors: ["清淡点"], spends: ["正常吃", "犒劳自己"], visual: "sushi" }),
  createFood("unagi-rice", "鳗鱼饭", "日料", "刺身寿司", { flavors: ["来点硬菜"], spends: ["正常吃", "犒劳自己"], visual: "rice" }),
  createFood("tonkotsu-ramen", "豚骨拉面", "日料", "拉面", { flavors: ["来点硬菜"], visual: "noodles" }),
  createFood("miso-ramen", "味噌拉面", "日料", "拉面", { flavors: ["来点硬菜"], visual: "noodles" }),
  createFood("tsukemen", "蘸面", "日料", "拉面", { flavors: ["来点硬菜"], visual: "noodles" }),
  createFood("chicken-katsu", "日式炸鸡排", "日料", "定食", { flavors: ["来点硬菜"], visual: "cutlet" }),
  createFood("beef-sukiyaki", "寿喜烧", "日料", "锅物", { flavors: ["来点硬菜"], spends: ["正常吃", "犒劳自己"], visual: "hotpot" }),
  createFood("takoyaki", "章鱼烧", "日料", "小食", { meals: ["午餐", "晚餐", "夜宵"], flavors: ["来点硬菜"], spends: ["简单吃"], visual: "snack" }),
  createFood("katsudon", "猪排饭", "日料", "定食", { flavors: ["来点硬菜"], visual: "rice" }),
  createFood("udon-noodles", "乌冬面", "日料", "面食", { flavors: ["清淡点"], visual: "noodles" }),

  createFood("bibimbap", "石锅拌饭", "韩餐", "拌饭", { flavors: ["想吃辣", "来点硬菜"], visual: "rice" }),
  createFood("kimchi-fried-rice", "泡菜炒饭", "韩餐", "拌饭", { flavors: ["想吃辣"], visual: "rice" }),
  createFood("bulgogi-rice", "烤肉拌饭", "韩餐", "拌饭", { flavors: ["来点硬菜"], visual: "rice" }),
  createFood("army-stew", "部队锅", "韩餐", "锅物", { flavors: ["想吃辣", "来点硬菜"], visual: "hotpot" }),
  createFood("kimchi-stew", "泡菜汤", "韩餐", "锅物", { flavors: ["想吃辣"], visual: "soup" }),
  createFood("tofu-stew", "嫩豆腐汤", "韩餐", "锅物", { flavors: ["想吃辣", "清淡点"], visual: "soup" }),
  createFood("korean-fried-chicken", "韩式炸鸡", "韩餐", "炸物", { meals: ["午餐", "晚餐", "夜宵"], flavors: ["想吃辣", "来点硬菜"], visual: "chicken" }),
  createFood("kimbap", "紫菜包饭", "韩餐", "小食", { meals: ["早餐", "午餐", "晚餐"], flavors: ["清淡点"], spends: ["简单吃"], visual: "roll" }),
  createFood("tteokbokki", "辣炒年糕", "韩餐", "小食", { meals: ["午餐", "晚餐", "夜宵"], flavors: ["想吃辣"], spends: ["简单吃"], visual: "snack" }),
  createFood("korean-bbq", "韩式烤五花肉", "韩餐", "烤肉", { flavors: ["来点硬菜"], spends: ["正常吃", "犒劳自己"], visual: "grill" }),
  createFood("cold-noodles", "韩式冷面", "韩餐", "面食", { flavors: ["清淡点"], visual: "noodles" }),

  createFood("pad-thai", "泰式炒河粉", "东南亚", "泰国菜", { flavors: ["想吃辣", "来点硬菜"], visual: "noodles" }),
  createFood("green-curry", "泰式绿咖喱", "东南亚", "泰国菜", { flavors: ["想吃辣", "来点硬菜"], visual: "curry" }),
  createFood("tom-yum-soup", "冬阴功汤", "东南亚", "泰国菜", { flavors: ["想吃辣"], visual: "soup" }),
  createFood("pho", "越南河粉", "东南亚", "越南菜", { flavors: ["清淡点", "来点硬菜"], visual: "noodles" }),
  createFood("banh-mi", "越南法棍", "东南亚", "越南菜", { meals: ["早餐", "午餐", "晚餐"], flavors: ["来点硬菜"], spends: ["简单吃"], visual: "sandwich" }),
  createFood("fresh-spring-rolls", "越南春卷", "东南亚", "越南菜", { flavors: ["清淡点"], spends: ["简单吃"], visual: "roll" }),
  createFood("nasi-goreng", "印尼炒饭", "东南亚", "印尼菜", { flavors: ["想吃辣", "来点硬菜"], visual: "rice" }),
  createFood("rendang-beef", "仁当牛肉", "东南亚", "印尼菜", { flavors: ["想吃辣", "来点硬菜"], visual: "beef" }),
  createFood("laksa", "叻沙", "东南亚", "马来菜", { flavors: ["想吃辣", "来点硬菜"], visual: "noodles" }),
  createFood("hainanese-chicken-rice", "海南鸡饭", "东南亚", "新加坡菜", { flavors: ["清淡点", "来点硬菜"], visual: "rice" }),
  createFood("satay", "沙爹串", "东南亚", "马来菜", { meals: ["午餐", "晚餐", "夜宵"], flavors: ["想吃辣", "来点硬菜"], visual: "skewers" }),

  createFood("classic-burger", "经典牛肉汉堡", "快餐小吃", "汉堡", { flavors: ["来点硬菜"], spends: ["简单吃"], visual: "burger" }),
  createFood("fried-chicken-burger", "炸鸡汉堡", "快餐小吃", "汉堡", { flavors: ["来点硬菜"], spends: ["简单吃"], visual: "burger" }),
  createFood("double-cheeseburger", "双层芝士汉堡", "快餐小吃", "汉堡", { flavors: ["来点硬菜"], spends: ["简单吃"], visual: "burger" }),
  createFood("original-fried-chicken", "原味炸鸡", "快餐小吃", "炸鸡", { meals: ["午餐", "晚餐", "夜宵"], flavors: ["来点硬菜"], spends: ["简单吃"], visual: "chicken" }),
  createFood("spicy-fried-chicken", "香辣炸鸡", "快餐小吃", "炸鸡", { meals: ["午餐", "晚餐", "夜宵"], flavors: ["想吃辣", "来点硬菜"], spends: ["简单吃"], visual: "chicken" }),
  createFood("fries", "薯条", "快餐小吃", "小食", { meals: ["午餐", "晚餐", "夜宵"], flavors: ["来点硬菜"], spends: ["简单吃"], visual: "fries" }),
  createFood("egg-tart", "葡式蛋挞", "快餐小吃", "小食", { meals: ["早餐", "下午茶"], flavors: ["想吃甜"], spends: ["简单吃"], visual: "tart" }),
  createFood("jianbing", "煎饼果子", "快餐小吃", "中式小吃", { meals: ["早餐", "午餐"], flavors: ["来点硬菜"], spends: ["简单吃"], visual: "crepe" }),
  createFood("stinky-tofu", "臭豆腐", "快餐小吃", "中式小吃", { meals: ["午餐", "晚餐", "夜宵"], flavors: ["想吃辣"], spends: ["简单吃"], visual: "snack" }),
  createFood("tacos", "墨西哥卷饼", "快餐小吃", "异国小吃", { flavors: ["想吃辣", "来点硬菜"], spends: ["简单吃"], visual: "taco" }),
  createFood("hot-dog", "热狗", "快餐小吃", "异国小吃", { meals: ["早餐", "午餐", "晚餐"], flavors: ["来点硬菜"], spends: ["简单吃"], visual: "hotdog" }),

  createFood("chicken-salad", "鸡胸肉沙拉", "轻食甜品", "轻食", { flavors: ["清淡点"], spends: ["简单吃"], visual: "salad" }),
  createFood("poke-bowl", "三文鱼波奇饭", "轻食甜品", "轻食", { flavors: ["清淡点"], spends: ["正常吃"], visual: "bowl" }),
  createFood("whole-wheat-sandwich", "全麦三明治", "轻食甜品", "轻食", { meals: ["早餐", "午餐"], flavors: ["清淡点"], spends: ["简单吃"], visual: "sandwich" }),
  createFood("yogurt-bowl", "酸奶碗", "轻食甜品", "轻食", { meals: ["早餐", "下午茶"], flavors: ["想吃甜", "清淡点"], spends: ["简单吃"], visual: "bowl" }),
  createFood("vegetable-wrap", "蔬菜卷", "轻食甜品", "轻食", { flavors: ["清淡点"], spends: ["简单吃"], visual: "roll" }),
  createFood("basque-cheesecake", "巴斯克芝士蛋糕", "轻食甜品", "蛋糕", { meals: ["下午茶", "夜宵"], flavors: ["想吃甜"], spends: ["简单吃"], visual: "cake" }),
  createFood("tiramisu", "提拉米苏", "轻食甜品", "蛋糕", { meals: ["下午茶", "夜宵"], flavors: ["想吃甜"], spends: ["正常吃"], visual: "cake" }),
  createFood("chocolate-mousse", "巧克力慕斯", "轻食甜品", "蛋糕", { meals: ["下午茶", "夜宵"], flavors: ["想吃甜"], spends: ["简单吃"], visual: "dessert" }),
  createFood("mango-pudding", "芒果布丁", "轻食甜品", "甜品", { meals: ["下午茶", "夜宵"], flavors: ["想吃甜"], spends: ["简单吃"], visual: "dessert" }),
  createFood("red-bean-shaved-ice", "红豆刨冰", "轻食甜品", "甜品", { meals: ["下午茶"], flavors: ["想吃甜", "清淡点"], spends: ["简单吃"], visual: "dessert" }),
  createFood("fruit-platter", "鲜切水果盘", "轻食甜品", "水果", { meals: ["早餐", "下午茶", "夜宵"], flavors: ["清淡点", "想吃甜"], spends: ["简单吃"], visual: "fruit" }),
]);

export function getFoodById(id) {
  return FOODS.find((food) => food.id === id);
}
